version: '3.8'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "5000:5000"

    volumes:
      - ./:/usr/api/
      - /usr/api/node_modules

    expose:
      - 5000

    command: npx ts-node ./src/index.ts

    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=postgres #has to be like that, if you change this you also need to change name of database service on line 31 from postgres to what ever you put here
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_LOGGING=${DB_LOGGING}
      - DB_SYNCHRONISE=${DB_SYNCHRONISE}
      - DB_DROP_TABLES_ON_SYNC=${DB_DROP_TABLES_ON_SYNC}
      - DB_SEED=${DB_SEED}
      - DB_TYPE=${DB_TYPE}
      - API_PORT=${API_PORT}
      - TOKEN_KEY=${TOKEN_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - MAIL_SERVICE_USERNAME=${MAIL_SERVICE_USERNAME}
      - MAIL_SERVICE_PASSWORD=${MAIL_SERVICE_PASSWORD}

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    expose:
      - 5432

 