version: '3.8'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    image: node:latest
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=postgres
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_PORT=${DB_PORT}
      - DB_LOGGING=${DB_LOGGING}
      - DB_SYNCHRONISE=${DB_SYNCHRONISE}
      - DB_DROPDB=${DB_DROPDB}
      - DB_TYPE=${DB_TYPE}
      - API_PORT=${API_PORT}
      - TOKEN_KEY=${TOKEN_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - MAIL_SERVICE_USERNAME=${MAIL_SERVICE_USERNAME}
      - MAIL_SERVICE_PASSWORD=${MAIL_SERVICE_PASSWORD}

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    expose:
      - 5432

 